# DasikLibrary Build Configuration
mod_name=DasikLibrary
mod_version=1.8.8
maven_group=net.dasik.social
archives_base_name=dasik-library

minecraft_version=26.2
loader_version=0.16.10
fabric_loader_version=0.16.10
fabric_version=0.152.1+26.2

# Publishing
modrinth_id=OQpYq8uX
curseforge_id=1192842
github_repo=Rifaditya/DasikLibrary-Rebuilt

org.gradle.java.home=E:/JDK25
fabric.loom.suppressJavaCompatibilityChecks=true
loom.suppressJavaCompatibilityChecks=true
