org.gradle.parallel=false

# Mod Properties
mod_name=DasikLibrary NF
mod_version=1.0.0+build.1
maven_group=net.dasik.social
archives_base_name=dasik-library-neoforge

# Dependencies
minecraft_version=26.1.2
parchment_minecraft_version=26.1.2
parchment_version=2026.01.22

# NeoForge
neoforge_version=26.1.2.43-beta

# Publishing IDs
modrinth_id=JVMIalSJ
curseforge_id=1453456
github_repo=Rifaditya/MC-DasikLibrary

